<div class="konten">
	<div class= "artikel">
		<h2>Artikel Kesehatan > Kesadaran Melakukan Medical Check Up </h2>
		<table>
		<th><img src="<?php echo base_url(); ?>assets/images/ak2.jpg"></th>
		<th><p><b>Jum'at 25 Desember 2015</b></p>
		  <p>Pemeriksaan kesehatan berkala, atau sering disebut medical check up, adalah suatu upaya pemeriksaan kesehatan menyeluruh yang mencakup pemeriksaan fisik, laboratorium dan penunjang diagnostik lain untuk mengetahui kondisi kesehatan seseorang dalam jangka waktu tertentu. “Medical check up sebaiknya dilakukan sebelum terjadi sakit, terutama bagi mereka yang sudah memasuki usia 25 tahun. Apalagi kalau di dalam keluarganya terdapat riwayat penyakit diabetes dan hipertensi, serta cenderung obesitas”, kata dr. Dyah Agustina W. selaku Presidium Pusat Perhimpunan Dokter Umum Indonesia (PDUI). Medical check up perlu dilakukan sejak usia muda mengingat saat ini banyak orang muda yang menerapkan gaya hidup tidak sehat. Mereka menyantap jenis makanan apapun asal enak tanpa melihat kandungan nutrisinya. Oleh karena itu, sangat dianjurkan bagi mereka untuk melakukan medical check up minimal 3-6 bulan sekali. Masalahnya, saat ini masih banyak orang yang takut dan merasa tidak perlu melakukan medical check up.  </p>
		  </th>
          <table>
		  <th><p>
 Sebagian dari mereka juga menganggap medical check up itu hanya buang-buang uang saja, karena buat apa kalau hasilnya normal.“Padahal, tujuan medical check up itu supaya kita dapat mengetahui sedini mungkin bila ada yang salah dengan kondisi kesehatan kita, sehingga pencegahan segera dapat dilakukan. Biaya pengobatan juga akan jauh lebih ringan dibandingkan bila harus mengobati penyakit yang sudah berada dalam tahap lanjut”, jelas dr. Dyah.</p>
		      <p> Jadi, kenapa  masih takut untuk melakukan <em>medical check up </em>? Dengan mengetahui lebih  dini adanya kelainan atau gangguan kesehatan, maka akan lebih mudah untuk  mengobatinya. &ldquo;Tanpa mengetahui gangguan fungsi tubuh yang sebenarnya terjadi,  tidak mudah untuk melakukan diagnosis dan menentukan terapinya. Semuanya itu  hanya dapat diketahui melalui pemeriksaan fisik, laboratorium dan penunjang  diagnostik lain. Dengan demikian, dokter pun dapat mendiagnosis dan menentukan  terapi serta pengobatan yang sesuai dan tepat&rdquo;, kata dr. Dyah. Jangan lagi ada  kata-kata, &ldquo;biarin aja deh, ntar aja kalau udah sakit&rdquo;, itu namanya sudah  terlambat. Bahkan, dengan mengetahui kelainan atau gangguan kesehatan lebih  dini, mungkin tidak perlu pengobatan karena masih dapat diatasi dengan mengubah  gaya hidup seperti harus rutin olah raga dan diet lemak.</p>
            <p>Berbeda  dengan mereka yang telah memahami manfaat <em>medical check up </em>dan secara  sadar telah rutin melakukannya, sekarang ini sebagian orang muda &ldquo;terpaksa&rdquo;  melakukan <em>medical check up </em>untuk keperluan memenuhi persyaratan  penerimaan karyawan baru. Banyak perusahaan di Indonesia yang telah menjadikan <em>medical  check up </em>sebagai suatu keharusan bagi calon karyawan maupun karyawannya  untuk kepentingan efisiensi dan produktivitas kerja karyawan. Kebijakan ini  dapat dimaklumi, karena bila angka kesakitan karyawan tinggi maka akan  menurunkan kinerja dan produktivitas perusahaan. Akibatnya, biaya pengobatan  yang dikeluarkan perusahaan akan menjadi lebih tinggi dan hal ini tentunya  sangat merugikan.</p>
            <p>Fenomena  lainnya yaitu <em>trend </em>melakukan <em>medical check up</em> di luar negeri di  kalangan masyarakat kelas atas. Padahal <em>medical check up </em>di Indonesia  sebetulnya tidak kalah dengan di luar negeri. &ldquo;Kalau hanya <em>medical check up  dasar</em>, itu kan prosedur sederhana jadi bisa dilakukan oleh laboratotium  klinik biasa, bahkan di Puskesmas yang lengkap pun juga bisa. Mungkin ada  faktor pertimbangan lain, misalnya masalah gengsi atau kenyamanan. Saya kira  mungkin lebih ke faktor kenyamanan, karena kadang-kadang orang melakukan  sesuatu perlu suasana yang nyaman&rdquo;, jelas dr. Dyah tentang sebagian orang  Indonesia yang lebih memilih melakukan <em>medical check up</em> di negara  tetangga. Selain itu, sebetulnya beragam panel pemeriksaan yang dibutuhkan juga  sudah tersedia di berbagai rumah sakit ataupun laboratorium klinik swasta di  Indonesia yang kontrol kualitasnya telah terstandar sangat baik. Oleh karena  itu, kenapa kita harus jauh-jauh ke luar negeri untuk melakukan <em>medical  check up </em>?</p>
<p><b>(Sumber : www.prodia.co.id)</bold> </p> 
        </br></th>
</table>

</div>
</div>